import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    price: 78,
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "images/fairy-tales.jpg",
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    year: 1836,
    category: "book",
  },

  {
    _id: uuid(),
    price: 878,
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "images/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    year: 1965,
    category: "book",
  },

  {
    _id: uuid(),
    price: 85,
    author: "Miguel de Cervantes",
    country: "Spain",
    imageLink: "images/don-quijote-de-la-mancha.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Don_Quixote\n",
    pages: 1056,
    title: "Don Quijote De La Mancha",
    year: 1610,
    category: "book",
  },

  {
    _id: uuid(),
    price: 698,
    author: "Alfred D\u00f6blin",
    country: "Germany",
    imageLink: "images/berlin-alexanderplatz.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    pages: 600,
    title: "Berlin Alexanderplatz",
    year: 1929,
    category: "book",
  },
  {
    _id: uuid(),
    price: 328,
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/crime-and-punishment.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    pages: 551,
    title: "Crime and Punishment",
    year: 1866,
    category: "book",
  },

  {
    _id: uuid(),
    price: 398,
    author: "William Faulkner",
    country: "United States",
    imageLink: "images/absalom-absalom.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    pages: 313,
    title: "Absalom, Absalom!",
    year: 1936,
    category: "book",
  },

  {
    _id: uuid(),
    price: 768,
    author: "Johann Wolfgang von Goethe",
    country: "Saxe-Weimar",
    imageLink: "images/faust.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    pages: 158,
    title: "Faust",
    year: 1832,
    category: "book",
  },
  {
    _id: uuid(),
    price: 978,
    author: "Nikolai Gogol",
    country: "Russia",
    imageLink: "images/dead-souls.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Dead_Souls\n",
    pages: 432,
    title: "Dead Souls",
    year: 1842,
    category: "book",
  },

  {
    _id: uuid(),
    price: 528,
    author: "Henrik Ibsen",
    country: "Norway",
    imageLink: "images/a-Dolls-house.jpg",
    language: "Norwegian",
    link: "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
    pages: 68,
    title: "A Doll's House",
    year: 1879,
    category: "book",
  },

  {
    _id: uuid(),
    price: 998,
    author: "Lu Xun",
    country: "China",
    imageLink: "images/diary-of-a-madman.jpg",
    language: "Chinese",
    link: "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
    pages: 389,
    title: "Diary of a Madman",
    year: 1918,
    category: "book",
  },
  {
    _id: uuid(),
    price: 458,
    author: "Naguib Mahfouz",
    country: "Egypt",
    imageLink: "images/children-of-gebelawi.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
    pages: 355,
    title: "Children of Gebelawi",
    year: 1959,
    category: "book",
  },
  {
    _id: uuid(),
    price: 428,
    author: "Thomas Mann",
    country: "Germany",
    imageLink: "images/buddenbrooks.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Buddenbrooks\n",
    pages: 736,
    title: "Buddenbrooks",
    year: 1901,
    category: "book",
  },

  {
    _id: uuid(),
    price: 888,
    author: "Michel de Montaigne",
    country: "France",
    imageLink: "images/essais.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
    pages: 404,
    title: "Essays",
    year: 1595,
    category: "book",
  },

  {
    _id: uuid(),
    price: 999,
    author: "Toni Morrison",
    country: "United States",
    imageLink: "images/beloved.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
    pages: 321,
    title: "Beloved",
    year: 1987,
    category: "book",
  },

  {
    _id: uuid(),
    price: 668,
    author: "Marcel Proust",
    country: "France",
    imageLink: "images/a-la-recherche-du-temps-perdu.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
    pages: 2408,
    title: "In Search of Lost Time",
    year: 1920,
    category: "book",
  },
  {
    _id: uuid(),
    price: 478,
    author: "Fran\u00e7ois Rabelais",
    country: "France",
    imageLink: "images/gargantua-and-pantagruel.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
    pages: 623,
    title: "Gargantua and Pantagruel",
    year: 1533,
    category: "book",
  },

  {
    _id: uuid(),
    price: 328,
    author: "Saadi",
    country: "Persia, Persian Empire",
    imageLink: "images/bostan.jpg",
    language: "Persian",
    link: "https://en.wikipedia.org/wiki/Bustan_(book)\n",
    pages: 298,
    title: "Bostan",
    year: 1257,
    category: "book",
  },

  {
    _id: uuid(),
    price: 448,
    author: "Jos\u00e9 Saramago",
    country: "Portugal",
    imageLink: "images/blindness.jpg",
    language: "Portuguese",
    link: "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
    pages: 352,
    title: "Blindness",
    year: 1995,
    category: "book",
  },

  {
    _id: uuid(),
    price: 238,
    author: "Italo Svevo",
    country: "Italy",
    imageLink: "images/confessions-of-zeno.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
    pages: 412,
    title: "Confessions of Zeno",
    year: 1923,
    category: "book",
  },
  {
    _id: uuid(),
    price: 128,
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/anna-karenina.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Anna_Karenina\n",
    pages: 864,
    title: "Anna Karenina",
    year: 1877,
    category: "book",
  },
];
