export const ACTION_TYPE = {
  SUCCESS: "SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_QTY_CART: "UPDATE_QTY_CART",
  INCREASE_QTY: "INCREASE_QTY",
  CLEAR_CART: "CLEAR_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};
